api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json:   ['application/json']
        html:   ['text/html']
        jsonld: ['application/ld+json']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
             apiKey:
                name: Authorization
                type: header

